language: ruby
rvm:
- 2.2.5
before_script:
- chmod +x ./script/cibuild.sh
script: "./script/cibuild.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  - provider: s3
    skip_cleanup: true
    local_dir: _site  
    access_key_id: AKIAJDXDS5JGY4XDUBJA
    bucket: aws-website-serraictcompanywebsite-a6r5y
    secret_access_key:
      secure: 3z9jQ63cgoh2sXIM/V+4z0S1PqNznfbYDqwJ79QUfDeuGWTaQXVXyw5o1u9QKT409qvEwot5zpE3sQBW7bcMMis9z54vdIOklgvKnLJ6Cj4TxXMr77nckFb6EWpmVI32t5Mq94GrhbMmRB6SBEfIOQQzBWFX5p8ku3fTQhOx0ounCLt4Aorc0Voys5a2uzEdm4aunG+St8+gnfsyTDSBA6VeRAWDMr+deCMPlig1lUO2DcvMIN88XPP+OwGLNDlkce0/BvppaHWLM8d6lQFLyYDWJbZhS6cJIExLcya3/N4y8mnwxbQEz3U3HqIgW0jqiCHqUA2vVu+YMaXsTh/WdUrrFZ/EEg6E+AxIWyCHXe+GZ/wzKvY673cwI/i+MQDSCWdAtYl94jiS8YJJO2Pefb9L5yqR2/8Ld5aO3wbrDq+HfjEp2CwK2IFL5krXGBBBHuBDS3upAhvDfeF6xguKO2hRbCNe1AVR5QqO7dUDMRKrzV5SZzM1/JhvkYypx1yTdRb/ZazkB28VamOLOSWDTPt/kTDXlneqG7xs1MT0raVEz0L6NASqJYUXwbf1KEo+uAXIRbpcd/ncLq5QfVnK1AwwC9XMyzjqMbf0FLMQqlYKw7ulrbdY6c7KcFOvIFmXI40WP2jNSIwoYjN9crULhbyjVx8HJzqasZCbMkaHWyc=
  - provider: firebase
    skip_cleanup: true
    local_dir: _site
    token:
      secure: "YOUR ENCRYPTED token"