language: ruby
rvm:
- 2.2.5
before_script:
- chmod +x ./script/cibuild.sh
script: "./script/cibuild.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
- provider: firebase
  skip_cleanup: true
  local_dir: _site
  token:
    secure: smB1mBiQL4rD15zrxqBEtjmPpIzlQOt3cNPqBCVLjRXsxxqHmmeFPslbTuVup0QmWoZCLYR/TCdtVbnHScmbXogXSws5MLY33JAmDW263T/Tpzw7idTAf2wOq7jm0QA59Z+D5HAkmSFivKK/mPu4cbuGafjV1vRIPoB27/IWJqQkgvhNdqIFldotXdb/d6BnGa3d+X6LfmJVP/1YDgzizSl1nDTh9LgqsaniWSa8iGjF31zA4gAm3rvzTaONGyUVFAzunFrzfdvet449Dtd0kAYUqQTyc9FWXRhcZBzIxLvbaKk6ozPgv153cvLRc2moGQ2S600itfQcTh/r8A5dAhz9k2qjau6C69Ja7NGTWQS9K8Qwk+v7Dk8fxxgJbRI7IuEZdlwgBwjP+ynQrPhE7DXtN3qh53SEPnTcYerh4z9sU3Feadp9EyQ3/hnA9yDs/F++FB14reGVWpa98pWpq+3N9Y31/PybRNLHPwHhyCkTEZslwpUtEl8q+swAzXhgZYwkhM+9i5PnG8aflda0gU8750RUN6LgwJ0ztzSNJbJDJMg0yGpUmK4QhI3m7SJg5dSBJVbNEjZy3gnrmHmMKmA9Q8gfQYQceYVrWx2MqNPV/pT0tvP/D54jE4qj94LuUjiohIjJ5bDoDdD+5FahzvIqD6xHl+Csu6WuL3n8pVM=
  project: serra-ict-website
